### ISSUE TITLE
Proposal build in endpoints should have different port then traffic endpoints

### ISSUE THREAD

**Issue by grumpy-programmer** [microdevs/missy#65]
Build in endpoints `/health`, `/info`, `/metrics` should have the option to configure them to different port than "traffic" endpoints.
Binding `/metrics` endpoint to the same port as traffic endpoints may cause a security issue. Showing metrics by misconfigured edge reverse-proxy/gateway could be harmful to the environment by exposing which technology you run, or sensitive business information you gathering by Prometheus client.

**Comment by mwarzynski** [comment]
@grumpy-programmer  Thanks for your report. I completely agree.

Actually, we are in the process of rewriting the project. Next version already includes changes that you proposed. Please, check out the branch `v1`.

If you have any other suggestions, we would love to get feedback from you.
